[book]
authors = ["GeekPie_HPC"]
language = "cn"
multilingual = false
src = "."
title = "GeekPie_HPC Wiki"

[build]
create-missing = false

[preprocessor.rmheader]
command = "python3 .preprocessor/rmheader.py"

[output.html]
git-repository-url = "https://github.com/geekpiehpc/wiki"
site-url = "/wiki/"
mathjax-support = true
