[book]
authors = ["GeekPie_HPC"]
language = "cn"
multilingual = false
src = "."
title = "GeekPie_HPC Wiki"

[build]
create-missing = false

[preprocessor.rmheader]
command = "python3 .preprocessor/rmheader.py"

[output.html]
git-repository-url = "https://github.com/geekpiehpc/wiki"
mathjax-support = true
site-url = "/wiki/"

[output.linkcheck]
exclude = ['homeservershow.com', 'www.supermicro.com', 'wikichip.org', 'geekpie.club', 'www.asrockrack.com', 'level1techs.com', 'www.station-drivers.com']
follow-web-links = true
traverse-parent-directories = false
